# For more info on HTTP files go to https://aka.ms/vs/httpfile

### get all
GET http://localhost:8086/api/Platform
content-type: application/json
charset=utf-8 

### get 1
GET http://localhost:8086/api/Platform/1
content-type: application/json
charset=utf-8 

### post new itam
POST http://localhost:8086/api/Platform
content-type: application/json
charset=utf-8 

{
  "name": "Apache",
  "publisher": "Apache Foundation",
  "cost": "Free"
}

### put itam
PUT http://localhost:8086/api/Platform
content-type: application/json
charset=utf-8 

{
  "id": 4,
  "name": "RabbitMQ Server",
  "publisher": "Rabbit Inc",
  "cost": "Free"
}